FROM golang:1.16 as build-stage
WORKDIR /go/src
ENV PATH="/go/bin:${PATH}"
RUN apt-get update && \
    apt-get install build-essential librdkafka-dev -y
COPY . .
RUN GOOS=linux go build -ldflags="-s -w" -o simulator
ENTRYPOINT ["./simulator"]